# Generated by Django 5.1.4 on 2026-07-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="crm.clientprofile",
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="audit_logs",
                to="core.job",
            ),
        ),
    ]
