# Generated by Django 5.1.4 on 2026-07-06 18:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtisanProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=20)),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("carpentry", "Carpentry & Joinery"),
                            ("upholstery", "Upholstery"),
                            ("finishing", "Finishing & Polishing"),
                            ("carving", "Carving & Engraving"),
                            ("welding", "Metal & Welding"),
                            ("general", "General Workshop"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "base_piece_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Default piece-rate per task in KES",
                        max_digits=10,
                    ),
                ),
                ("nssf_number", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_at", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Artisan",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SupplierProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("contact_name", models.CharField(blank=True, max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("timber", "Timber"),
                            ("hardware", "Hardware & Fittings"),
                            ("upholstery", "Upholstery Fabric"),
                            ("finish", "Finishes & Oils"),
                            ("adhesives", "Adhesives & Chemicals"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("gikomba", "Gikomba Market"),
                            ("ngara", "Ngara"),
                            ("ngong", "Ngong Road"),
                            ("mombasa", "Mombasa Road"),
                            ("other", "Other"),
                        ],
                        default="gikomba",
                        max_length=20,
                    ),
                ),
                (
                    "current_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Current price per BF (timber) or per unit (hardware) in KES",
                        max_digits=10,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Supplier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "po_number",
                    models.CharField(editable=False, max_length=25, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("raised", "Raised"),
                            ("confirmed", "Confirmed by Supplier"),
                            ("received", "Goods Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="raised",
                        max_length=15,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Items ordered, quantities, specifications"
                    ),
                ),
                (
                    "estimated_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "unit_cost_at_receipt",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Locked when goods are received — auto-propagated to linked BOM entries",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("raised_at", models.DateTimeField(auto_now_add=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="partners.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Purchase Order",
                "ordering": ["-raised_at"],
            },
        ),
        migrations.CreateModel(
            name="SupplierRateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("effective_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_history",
                        to="partners.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supplier Rate History",
                "ordering": ["-created_at"],
            },
        ),
    ]
