# Generated by Django 5.1.4 on 2026-07-06 18:51

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("partners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=True,
                        help_text="Locked until brief approved + deposit paid",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("workshop_notes", models.TextField(blank=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("target_completion", models.DateField(blank=True, null=True)),
                ("actual_completion", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_card",
                        to="core.job",
                    ),
                ),
                (
                    "unlocked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Card",
            },
        ),
        migrations.CreateModel(
            name="HardwareEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_name",
                    models.CharField(
                        help_text="e.g. Piano hinge 3-inch, M6 bolt", max_length=200
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2, help_text="KES per unit", max_digits=10
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimated (from Quote)"),
                            ("actual", "Actual (Workshop Record)"),
                        ],
                        default="estimated",
                        max_length=15,
                    ),
                ),
                ("date_purchased", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hardware_entries",
                        to="partners.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.supplierprofile",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hardware_entries",
                        to="production.jobcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hardware Entry",
                "verbose_name_plural": "Hardware Entries",
            },
        ),
        migrations.CreateModel(
            name="LaborEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_description", models.CharField(max_length=300)),
                (
                    "piece_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="KES for this task/piece",
                        max_digits=10,
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Optional — for hourly billing verification",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimated (from Quote)"),
                            ("actual", "Actual (Workshop Record)"),
                        ],
                        default="estimated",
                        max_length=15,
                    ),
                ),
                ("work_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "artisan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.artisanprofile",
                    ),
                ),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_entries",
                        to="production.jobcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Labour Entry",
                "verbose_name_plural": "Labour Entries",
            },
        ),
        migrations.CreateModel(
            name="TimberEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "species",
                    models.CharField(
                        choices=[
                            ("mahogany", "Mahogany (Meliaceae)"),
                            ("mvule", "Mvule / African Teak"),
                            ("pine", "Pine (Softwood)"),
                            ("cedar", "East African Cedar"),
                            ("elgon", "Elgon Olive"),
                            ("camphor", "Camphor"),
                            ("nandi", "Nandi Flame"),
                            ("other", "Other / Mixed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "board_feet",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Board feet consumed (1 BF = 1ft × 1ft × 1in)",
                        max_digits=8,
                    ),
                ),
                (
                    "unit_cost_per_bf",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="KES per board foot (locked from PO receipt if linked)",
                        max_digits=10,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        editable=False,
                        max_digits=12,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("estimated", "Estimated (from Quote)"),
                            ("actual", "Actual (Workshop Record)"),
                        ],
                        default="estimated",
                        max_length=15,
                    ),
                ),
                ("date_purchased", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "job_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timber_entries",
                        to="production.jobcard",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timber_entries",
                        to="partners.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="partners.supplierprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Timber Entry",
                "verbose_name_plural": "Timber Entries",
            },
        ),
    ]
