# Generated by Django 5.1.4 on 2026-07-06 18:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CareSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "care_type",
                    models.CharField(
                        choices=[
                            ("board_butter", "Board Butter / Oil Treatment"),
                            ("polish", "Polish & Clean"),
                            ("structural", "Structural Check"),
                            ("refinishing", "Refinishing"),
                        ],
                        max_length=20,
                    ),
                ),
                ("due_date", models.DateField()),
                ("notification_sent", models.BooleanField(default=False)),
                ("completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("piece_name", models.CharField(max_length=200)),
                (
                    "client_name_display",
                    models.CharField(
                        default="Private Collection",
                        help_text="Client name or 'Private Collection' for anonymous",
                        max_length=200,
                    ),
                ),
                (
                    "species_used",
                    models.JSONField(
                        default=list,
                        help_text="List of species used, e.g. ['Mvule', 'Mahogany']",
                    ),
                ),
                (
                    "total_board_feet",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("completion_date", models.DateField()),
                ("care_instructions", models.TextField(blank=True)),
                (
                    "qr_code_url",
                    models.URLField(
                        blank=True, help_text="Auto-generated QR code image URL"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-completion_date"],
            },
        ),
    ]
