# Generated by Django 5.1.4 on 2026-07-06 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("certificates", "0001_initial"),
        ("core", "0001_initial"),
        ("partners", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="certificate",
            name="job",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="certificate",
                to="core.job",
            ),
        ),
        migrations.AddField(
            model_name="certificate",
            name="primary_artisan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="partners.artisanprofile",
            ),
        ),
        migrations.AddField(
            model_name="careschedule",
            name="certificate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="care_schedules",
                to="certificates.certificate",
            ),
        ),
    ]
