# Generated by Django 5.1.4 on 2026-07-06 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("secondary_phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("county", models.CharField(blank=True, max_length=50)),
                (
                    "acquisition_source",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("referral", "Referral"),
                            ("whatsapp", "WhatsApp"),
                            ("walk_in", "Walk-In"),
                            ("website", "Website"),
                            ("auction", "Auction"),
                            ("exhibition", "Exhibition"),
                            ("other", "Other"),
                        ],
                        default="referral",
                        max_length=30,
                    ),
                ),
                (
                    "preference_notes",
                    models.TextField(
                        blank=True,
                        help_text="Species preferences, style notes, budget hints",
                    ),
                ),
                ("is_vip", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Interaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone Call"),
                            ("email", "Email"),
                            ("site", "Website"),
                            ("in_person", "In Person"),
                            ("sms", "SMS"),
                        ],
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(help_text="Summary of the interaction")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interactions",
                        to="crm.clientprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interactions",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("inquiry", "Inquiry"),
                            ("quoted", "Quoted"),
                            ("negotiating", "Negotiating"),
                            ("approved", "Design Approved"),
                            ("production", "In Production"),
                            ("delivered", "Delivered"),
                            ("retained", "Retained Client"),
                            ("lost", "Lost"),
                        ],
                        default="inquiry",
                        max_length=20,
                    ),
                ),
                (
                    "piece_type",
                    models.CharField(
                        help_text="e.g. 6-seater dining set, TV unit", max_length=100
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leads",
                        to="crm.clientprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DesignBrief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="Full design specification"),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True, help_text="L × W × H in mm or cm", max_length=200
                    ),
                ),
                (
                    "primary_species",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Mvule, Mahogany, Pine",
                        max_length=100,
                    ),
                ),
                (
                    "finish",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Natural oil, Teak oil, Paint",
                        max_length=100,
                    ),
                ),
                (
                    "attachments_url",
                    models.URLField(
                        blank=True,
                        help_text="Cloudinary folder URL or design render link",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent to Client"),
                            ("revision", "Under Revision"),
                            ("approved", "Approved by Client"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="design_briefs",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("job", "version")},
            },
        ),
    ]
