# Generated by Django 5.1.4 on 2026-07-06 18:51

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("crm", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dining", "Dining"),
                            ("bedroom", "Bedroom"),
                            ("living", "Living Room"),
                            ("office", "Office"),
                            ("outdoor", "Outdoor"),
                            ("storage", "Storage & Shelving"),
                            ("custom", "Custom Commission"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "primary_species",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Mvule, Mahogany, Pine",
                        max_length=100,
                    ),
                ),
                (
                    "starting_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "lead_time_days",
                    models.PositiveIntegerField(
                        default=30, help_text="Typical lead time in calendar days"
                    ),
                ),
                (
                    "whatsapp_cta",
                    models.CharField(
                        default="+254700000000",
                        help_text="WhatsApp number for enquiries (with country code)",
                        max_length=20,
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Product",
                "ordering": ["-is_featured", "name"],
            },
        ),
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("piece_of_interest", models.CharField(max_length=200)),
                (
                    "budget_range",
                    models.CharField(
                        choices=[
                            ("under_50k", "Under KES 50,000"),
                            ("50k_150k", "KES 50,000 – 150,000"),
                            ("150k_300k", "KES 150,000 – 300,000"),
                            ("300k_500k", "KES 300,000 – 500,000"),
                            ("over_500k", "Over KES 500,000"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "timeline_months",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="How soon the client needs the piece (months)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("contacted", "Contacted"),
                            ("converted", "Converted to Client"),
                            ("removed", "Removed"),
                        ],
                        default="active",
                        max_length=15,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Waitlist Entry",
                "verbose_name_plural": "Waitlist Entries",
                "ordering": ["budget_range", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="AuctionLot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image_url", models.URLField(blank=True)),
                ("starting_bid", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "current_bid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("extended", "Extended (Anti-Snipe)"),
                            ("closed", "Closed"),
                            ("sold", "Sold"),
                        ],
                        default="draft",
                        max_length=15,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                (
                    "anti_snipe_minutes",
                    models.PositiveIntegerField(
                        default=5,
                        help_text="If a bid arrives in the final N minutes, extend end_time by N minutes.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="won_auctions",
                        to="crm.clientprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="storefront.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Auction Lot",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="AuctionBid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_proxy", models.BooleanField(default=False)),
                (
                    "max_proxy_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("placed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "bidder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.clientprofile",
                    ),
                ),
                (
                    "lot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bids",
                        to="storefront.auctionlot",
                    ),
                ),
            ],
            options={
                "ordering": ["-amount"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.URLField(help_text="Cloudinary URL")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="storefront.product",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
