# Generated by Django 5.1.4 on 2026-07-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="waitlist",
            name="reference_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="waitlist_references/"
            ),
        ),
    ]
