# Generated by Django 5.1.4 on 2026-07-09 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_waitlist_reference_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionbid',
            name='bidder_phone',
            field=models.CharField(blank=True, help_text='Snapshot of phone used at time of bid', max_length=20, null=True),
        ),
    ]
