# Generated by Django 5.1.4 on 2026-07-10 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_auctionbid_bidder_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlot',
            name='image_url',
            field=models.URLField(blank=True, help_text='Override URL if different from linked product primary media'),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='budget_range',
            field=models.CharField(choices=[('under_50k', 'Under KES 50,000'), ('50k_150k', 'KES 50,000 – 150,000'), ('150k_300k', 'KES 150,000 – 300,000'), ('300k_500k', 'KES 300,000 – 500,000'), ('over_500k', 'Over KES 50,000')], max_length=15),
        ),
        migrations.AlterField(
            model_name='waitlist',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('contacted', 'Contacted'), ('follow up', 'Follow Up'), ('converted', 'Converted to Client'), ('cancelled', 'Cancelled')], default='active', max_length=15),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], default='IMAGE', max_length=10)),
                ('media_url', models.URLField(help_text='Cloudinary URL for the image or video file')),
                ('thumbnail_url', models.URLField(blank=True, help_text='Optional thumbnail URL, especially useful for video media')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='If true, this will be the main display item (usually an image)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='storefront.product')),
            ],
            options={
                'verbose_name_plural': 'Product Media',
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
