# Generated by Django 5.1.4 on 2026-07-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0004_alter_auctionlot_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='architectural_drawing_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for the architectural drawing, 2D blueprint, or dimension layout diagram'),
        ),
        migrations.AddField(
            model_name='product',
            name='depth_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Depth of the item in cm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Height of the item in cm', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width_cm',
            field=models.PositiveIntegerField(blank=True, help_text='Width/Length of the item in cm', null=True),
        ),
    ]
